#Placeholder's
#Default Minecraft Color codes work example
#"&b&l%player%&f: &8%message%"
#%player% is replaced with the Players name that sent the message
#%message% Is replaced with the message sent by the player

#Player Msg/Whisper/Tell Configuration

#Message Receive/send
playermsgsend: "&7&oMessage To &7%player%:%message%"
playermsgrecieve: "&7&oMessage From %player%&7&o:%message%"

#Tell Receive/send
playertellsend: "&7&oTell To %player%&7&o:%message%"
playertellrecieve: "&7&oTell From %player%&7&o:%message%"

#Whisper Receive/send
playerwsend: "&7&oWhisper To %player%&7&o:%message%"
playerwrecieve: "&7&oWhisper From %player%&7&o:%message%"


#Server Msg/Whisper/Tell Configuration

#Console/Server-name to be sent with the Messages
servername: "Console"

#Message Receive/send
servermsgsend: "&7&oMessage To %player%&7&o&7:%message%"
servermsgrecieve: "&7&oMessage From %server%&7:%message%"

#Tell Receive/send
servertellsend: "&7&oTell To %player%&7:%message%"
servertellrecieve: "&7&oTell From %server%&7:%message%"


#Whisper Receive/send
serverwsend: "&7&oWhisper To %player%&7:%message%"
serverwrecieve: "&7&oWhisper From %server%&7:%message%"