#Placeholder's
#Default Minecraft Color codes work example
#"&b&l%player%&f: &8%message%"
#%player% is replaced with the Players name that sent the message
#%message% Is replaced with the message sent by the player

#Player Msg/Whisper/Tell Configuration

#Message Receive/send
playermsgsend: "&dMessage To &7%player%:%message%"
playermsgrecieve: "&dMessage From %player%&d:%message%"

#Tell Receive/send
playertellsend: "&dTell To %player%&d:%message%"
playertellrecieve: "&dTell From %player%&d:%message%"

#Whisper Receive/send
playerwsend: "&dWhisper To %player%&d:%message%"
playerwrecieve: "&dWhisper From %player%&d:%message%"


#Server Msg/Whisper/Tell Configuration

#Console/Server-name to be sent with the Messages
servername: "Console"

#Message Receive/send
servermsgsend: "&4&lMessage To %server%&d&7:%message%"
servermsgrecieve: "&4&lMessage From %server%&7:%message%"

#Tell Receive/send
servertellsend: "&4&lTell To %server%&7:%message%"
servertellrecieve: "&4&lTell From %server%&7:%message%"


#Whisper Receive/send
serverwsend: "&4&lWhisper To %server%&7:%message%"
serverwrecieve: "&4&lWhisper From %server%&7:%message%"